version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase
      - REDIS_URL=redis://cache:6379
    depends_on:
      - db
      - cache
    networks:
      - my_network
    ports:
      - "8000:8000"  # Change port as needed

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network

  cache:
    image: redis:latest
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data: